placos:
  Outdoor Temperature: 22
  Outdoor Hygro: 35
  Max Indoor Temperature: 40
  Light Time Constant: 100
  Ventillation Time Constant: 10
  Thread Refresh Rate: 0.1

pins:
  - dbusname: Pin_1
    variable: inTemp
    method: dummy
    
  - dbusname: Pin_2
    variable: outTemp
    method: dummy    
    
  - dbusname: Pin_3
    variable: eclairage
    method: setEclairage

  - dbusname: Pin_4
    variable: ventilation
    method: setVentilation

  - dbusname: Pin_5
    variable: outHygroSensor
    method: dummy    

  - dbusname: Pin_6
    variable: inHygroSensor
    method: dummy

interupts:
  - variable: inTemp
    threshold: 26
    
  - variable: inHygroSensor
    threshold: 70

allow notify: yes
