placos:
  Outdoor Temperature: 22
  Outdoor Hygro: 35
  Max Indoor Temperature: 40
  Light Time Constant: 100
  Ventillation Time Constant: 10
  Thread Refresh Rate: 0.1

devices:
  indoor_Temperature:
    kind: sensor
    VPvariable: inTemp

  outdoor_Temperature:
    kind: sensor
    VPvariable: outTemp
    
  indoor_Hygro:
    kind: sensor
    VPvariable: inHygroSensor

  outdoor_Hygro:
    kind: sensor
    VPvariable: outHygroSensor    

  eclairage:
    kind: actuator
    VPmethod: setEclairage

  ventilation:
    kind: actuator
    VPmethod: setVentilation

pins:
  Pin_1: indoor_Temperature
  Pin_2: outdoor_Temperature   
  Pin_3: eclairage
  Pin_4: ventilation
  Pin_5: outdoor_Hygro
  Pin_6: indoor_Hygro

interupts:
  - variable: inTemp
    threshold: 26
    
  - variable: inHygroSensor
    threshold: 70

