
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
# uncomment this line if your project needs to run something other than `rake`:
script: dbus-launch bundle exec rspec test/*_rspec.rb
after_script:  cat server/opos-daemon.log
