objects:

- name: Temperature Indoor
  path: /home/indoor/Temperature
  model: Generic_Celsius_Temperature
  regul:
    action-: /home/indoor/Fan
    frequency: 2
    type: "pwm_regul"
   
- name: Temperature Outdoor
  path: /home/outdoor/Temperature
  model: Generic_Celsius_Temperature

- name: Hygrometrie Outdoor
  path: /home/outdoor/Hygro
  model: VirtualPlacos_Hygro
  depends:
    temp: /home/outdoor/Temperature
     
- name: Hygrometrie Indoor
  path: /home/indoor/Hygro
  model: VirtualPlacos_Hygro
  depends:
    temp: /home/indoor/Temperature
  regul:
    action-: /home/indoor/Fan
    frequency: 0.5
  plugin_fill_sql_frequency: 2

    
- name: Light
  path: /home/indoor/Light
  model: Generic_relay_NO
    
- name: Fan
  path: /home/indoor/Fan
  model: Generic_pwm

# drivers are in drivers folder
card:
- name: VirtualPlacos
  exec: VirtualPlacos/VirtualPlacos.rb
  config: config.yaml
  timeout: 2
  plug: 
    /Pin_1: /home/indoor/Temperature
    /Pin_2: /home/outdoor/Temperature
    /Pin_3: /home/indoor/Light
    /Pin_4: /home/indoor/Fan
    /Pin_5: /home/outdoor/Hygro
    /Pin_6: /home/indoor/Hygro

# plugins are in plugins folder
plugins:

- name: sql
  method: fork
  exec: sql.rb

- name: fill_sql
  method: disable
  exec: fill_sql.rb

- name: ror_frontend
  method: disable
  exec: ror_frontend.rb

- name: log
  method: disable
  exec: log.rb
  file: /tmp/opos2.log
  
- name: xmlrpc
  method: disable
  exec: xmlrpc.rb
  port: 8080
  
- name: soap
  method: disable
  exec: soap.rb
  port: 8081

user:

#no password
- login: anonymous
  permissions:
    read: all
    
# password : test
- login: user1
  hash: '325636066ccb24500a9f1a0df376965118e59230'
  permissions:
    read: all
    write: actuators
    exclude: /home/indoor/Fan

# password : test
- login: user2
  hash: '325636066ccb24500a9f1a0df376965118e59230'
  permissions:
    read: /home/outdoor/

# password : password
- login: admin
  hash: '5e38fb24e0314e2b3ec2caa2931c147442960ed4'
  permissions:
    write: all
