objects:

- name: VirtualPlacos
  path: /home/indoor/Virtualplacos
  config: config.yaml
  exec: VirtualPlacos/VirtualPlacos.rb	

- name: sql
  method: disable
  exec: sql.rb

- name: log
  method: fork
  exec: log.rb
  file: /tmp/opos2.log

- name: fill_sql
  method: thread
  exec: fill_sql.rb
