objects:

- name: Temperature_indoor
  path: /home/Temperature_indoor
  model: Generic_Celsius_Temperature
   
- name: Temperature_outdoor
  path: /home/Temperature_outdoor
  model: Generic_Celsius_Temperature

- name: Hygro_out
  path: /home/Hygro_out
  model: VirtualPlacos_Hygro
  depends:
    temp: /home/Temperature_outdoor
     
- name: Hygro_in
  path: /home/Hygro_in
  model: VirtualPlacos_Hygro
  depends:
    temp: /home/Temperature_indoor

- name: Light
  path: /home/Light
  model: Generic_relay_NO
    
- name: Fan
  path: /home/Fan
  model: Generic_relay_NO

card:
- name: VirtualPlacos
  plug: 
    /Pin_1: /home/Temperature_indoor
    /Pin_2: /home/Temperature_outdoor
    /Pin_3: /home/Light
    /Pin_4: /home/Fan
    /Pin_5: /home/Hygro_out
    /Pin_6: /home/Hygro_in

