objects:

- name: Temperature Indoor
  path: /home/indoor/Temperature
  model: Generic_Celsius_Temperature
  regul:
    action-: /home/indoor/Fan
   
- name: Temperature Outdoor
  path: /home/outdoor/Temperature
  model: Generic_Celsius_Temperature

- name: Hygrometrie Outdoor
  path: /home/outdoor/Hygro
  model: VirtualPlacos_Hygro
  depends:
    temp: /home/outdoor/Temperature
     
- name: Hygrometrie Indoor
  path: /home/indoor/Hygro
  model: VirtualPlacos_Hygro
  depends:
    temp: /home/indoor/Temperature
  regul:
    action-: /home/indoor/Fan
    frequency: 0.5
    
- name: Light
  path: /home/indoor/Light
  model: Generic_relay_NO
    
- name: Fan
  path: /home/indoor/Fan
  model: Generic_relay_NO

card:
- name: VirtualPlacos
  plug: 
    /Pin_1: /home/indoor/Temperature
    /Pin_2: /home/outdoor/Temperature
    /Pin_3: /home/indoor/Light
    /Pin_4: /home/indoor/Fan
    /Pin_5: /home/outdoor/Hygro
    /Pin_6: /home/indoor/Hygro

plugins:

#~ - name: log
  #~ method: fork
  #~ exec: plugins/log.rb
  #~ 
#~ - name: xmlrpc
  #~ method: fork
  #~ exec: plugins/xmlrpc.rb
  #~ 
#~ - name: soap
  #~ method: thread
  #~ exec: plugins/soap.rb
  
- name: sql
  method: fork
  exec: plugins/sql.rb

