card:
- name: VirtualPlacos
  interface: org.openplacos.driver.analog
  driver: org.openplacos.drivers.virtualplacos
  object: 
    Temperature_indoor:  Pin_1
    Temperature_outdoor:  Pin_2
    light:  Pin_3
    fan:  Pin_4
    Hygro_out:  Pin_5
    Hygro_in: Pin_6
    
    
measure:
- name: Temperature_indoor
  
- name: Hygro_in
  interface: org.openplacos.drivers.level1.convert
  driver: org.openplacos.drivers.level1.Hygro
  object: 
    - org/openplacos/drivers/level1/Convert
  dep_list:
    - Temperature_indoor
