measure:
- name: Temperature_indoor
  room: indoor
  model: Generic_Celsius_Temperature
   
- name: Temperature_outdoor
  room: outdoor
  model: Generic_Celsius_Temperature

- name: Hygro_out
  room: outdoor
  model: VirtualPlacos_Hygro
  depends:
    temp: Temperature_outdoor
     
- name: Hygro_in
  room: indoor
  model: VirtualPlacos_Hygro
  depends:
    temp: Temperature_indoor

actuator:
- name: Light
  room: indoor
  model: Generic_relay_NO
    
- name: Fan
  room: indoor
  model: Generic_relay_NO


card:
- name: uChameleon
  plug: 
    pin_1: Temperature_indoor
    pin_2: Temperature_outdoor
    pin_3: Light
    pin_4: Fan
    pin_5: Hygro_out
    pin_6: Hygro_in

