objects:

#~ - name: log
  #~ method: disable
  #~ exec: log.rb
  #~ config:
    #~ file: /tmp/opos2.log

- name: driver
  exec: driver.rb
  method: thread
  
- name: temperature
  exec: temperature_compact.rb
  method: thread


mapping:
- /temperature/raw: /driver/Pin_1
