objects:

#~ - name: log
  #~ method: disable
  #~ exec: log.rb
  #~ config:
    #~ file: /tmp/opos2.log

- name: simpleplacos
  exec: simple_placos.rb
  method: fork
  
- name: temperature2
  exec: temperature.rb
  method: fork

- name: temperature3
  exec: temperature.rb
  method: fork


mapping:
- /temperature2/raw: /simpleplacos/Pin_1
- /temperature3/raw: /temperature2/Temperature
