objects:

#~ - name: log
  #~ method: disable
  #~ exec: log.rb
  #~ config:
    #~ file: /tmp/opos2.log

- name: simpleplacos
  exec: simple_placos.rb
  method: fork
  
- name: temperature
  exec: temperature.rb
  method: disable

mapping:
- /temperature/raw: /simpleplacos/Pin_1
