objects:

- name: Temperature Indoor
  path: /home/Temperature_indoor
  model: Generic_Celsius_Temperature
  regul:
    action-: /home/Fan
   
- name: Temperature Outdoor
  path: /home/Temperature_outdoor
  model: Generic_Celsius_Temperature

- name: Hygrometrie Outdoor
  path: /home/Hygro_out
  model: VirtualPlacos_Hygro
  depends:
    temp: /home/Temperature_outdoor
     
- name: Hygrometrie Indoor
  path: /home/Hygro_in
  model: VirtualPlacos_Hygro
  depends:
    temp: /home/Temperature_indoor
  regul:
    action-: /home/Fan
    
- name: Light
  path: /home/Light
  model: Generic_relay_NO
    
- name: Fan
  path: /home/Fan
  model: Generic_relay_NO

card:
- name: VirtualPlacos
  plug: 
    /Pin_1: /home/Temperature_indoor
    /Pin_2: /home/Temperature_outdoor
    /Pin_3: /home/Light
    /Pin_4: /home/Fan
    /Pin_5: /home/Hygro_out
    /Pin_6: /home/Hygro_in

#database: 
#  name: opos_VP
#  adapter: mysql
#  host: localhost
#  user: root
# Please set password in $OPOS_PASS 
#  profile: measures, actuators, users 
#  include: 
#  exclude:  Temperature_outdoor, Hygro_out

