export:
- /home/temperature

component:
#~ - name: log
  #~ method: disable
  #~ exec: log.rb
  #~ config:
    #~ file: /tmp/opos2.log

- name: driver
  exec: driver.rb
  method: fork
  
- name: temperature2
  exec: temperature_compact.rb
  method: fork

- name: temperature3
  exec: temperature_compact.rb
  method: fork


mapping:
- /temperature2/raw: /simpleplacos/Pin_1
- /temperature3/raw: /temperature2/Temperature
- /home/temperature: /temperature3/Temperature
