card:
- name: uCham
  interface: org.openplacos.driver.uChamInterface
  driver: org.openplacos.drivers.uChameleon
  object: 
    device_1:  pin_1 
    device_2:  pin_2 
    device_3:  pin_3 
    device_4:  pin_4 
    device_5:  pin_5 
    device_6:  pin_6
    device_7:  pin_7
    device_8:  pin_8
    device_9:  pin_9
    device_10: pin_10
    device_11: pin_11
    device_12: pin_12
    device_13: pin_13
    device_14: pin_14
    device_15: pin_15
    device_16: pin_16
    device_17: pin_17

measure:
- name: device_1
  interface: org.openplacos.drivers.level1.convert
  driver: org.openplacos.drivers.level1.convert
  object: 
    - org/openplacos/drivers/level1/Convert

    
- name: device_2
  interface: org.openplacos.drivers.level1.convert
  driver: org.openplacos.drivers.level1.convert
  object: 
    - org/openplacos/drivers/level1/Convert
  dep_list:
    - device_1