measure:
- name: Temperature_indoor
  room: indoor
  model: Generic_Celsius_Temperature
   
- name: Temperature_outdoor
  room: outdoor
  model: Generic_Celsius_Temperature

- name: Hygro_out
  room: outdoor
  model: VirtualPlacos_Hygro
  depends:
    temp: Temperature_outdoor
     
- name: Hygro_in
  room: indoor
  model: VirtualPlacos_Hygro
  depends:
    temp: Temperature_indoor

actuator:
- name: Light
  room: indoor
  model: Generic_relay_NO
    
- name: Fan
  room: indoor
  model: Generic_relay_NO

card:
- name: VirtualPlacos
  plug: 
    /Pin_1: Temperature_indoor
    /Pin_2: Temperature_outdoor
    /Pin_3: Light
    /Pin_4: Fan
    /Pin_5: Hygro_out
    /Pin_6: Hygro_in

database: 
  name: opos_VP
  adapter: mysql
  host: localhost
  user: root
  password: 

