measure:
- name: Temperature_indoor
   
- name: Temperature_outdoor
 
- name: Light

- name: Fan

- name: Hygro_out
 
- name: Hygro_in
  driver: org.openplacos.drivers.virtualplacos_hygrosensor
    depends:
    temp: Temperature_indoor

card:
- name: VirtualPlacos
  driver: org.openplacos.drivers.virtualplacos
  plug: 
    Pin_1: Temperature_indoor
    Pin_2: Temperature_outdoor
    Pin_3: Light
    Pin_4: Fan
    Pin_5: Hygro_out
    Pin_6: Hygro_in
