export:
- /home/temperature

component:
#~ - name: log
  #~ method: disable
  #~ exec: log.rb
  #~ config:
    #~ file: /tmp/opos2.log

- name: driver2
  exec: driver.rb
  method: thread
  
- name: temperature
  exec: temperature_compact.rb
  method: debug

mapping:
- /temperature/raw: /driver2/Pin_1
- /home/temperature: /temperature/temperature
