- name: uCham
  interface: org.openplacos.driver.uChamInterface
  driver: org.openplacos.drivers.uChameleon
  object: 
    device 1:  pin_1 
    device 2:  pin_2 
    device 3:  pin_3 
    device 4:  pin_4 
    device 5:  pin_5 
    device 6:  pin_6
    device 7:  pin_7
    device 8:  pin_8
    device 9:  pin_9
    device 10: pin_10
    device 11: pin_11
    device 12: pin_12
    device 13: pin_13
    device 14: pin_14
    device 15: pin_15
    device 16: pin_16
    device 17: pin_17
