measure:
- name: Temperature_indoor
  model: Generic_Celsius_Temperature
   
- name: Temperature_outdoor
  model: Generic_Celsius_Temperature

- name: Hygro_out
  model: VirtualPlacos_Hygro
  depends:
    temp: Temperature_outdoor
     
- name: Hygro_in
  model: VirtualPlacos_Hygro
  depends:
    temp: Temperature_indoor

actuator:
- name: Light
  model: Generic_relay_NO

- name: Fan
  model: Generic_relay_NO

card:
- name: VirtualPlacos
  plug: 
    Pin_1: Temperature_indoor
    Pin_2: Temperature_outdoor
    Pin_3: Light
    Pin_4: Fan
    Pin_5: Hygro_out
    Pin_6: Hygro_in
