objects:

- name: Temperature Paris
  path: /weather/Paris/temperature
  model: Generic_Celsius_Temperature

- name: Temperature Grenoble
  path: /weather/Grenoble/temperature
  model: Generic_Celsius_Temperature

- name: Temperature Berlin
  path: /weather/Berlin/temperature
  model: Generic_Celsius_Temperature

- name: Humidity Paris
  path: /weather/Paris/humidity
  model: Generic_Humidity

- name: Humidity Grenoble
  path: /weather/Grenoble/humidity
  model: Generic_Humidity

- name: Humidity Berlin
  path: /weather/Berlin/humidity
  model: Generic_Humidity             
       
- name: Wind Paris
  path: /weather/Paris/wind
  model: Wind_Speed

- name: Wind Paris
  path: /weather/Paris/wind
  model: Wind_Speed
  
- name: Wind Grenoble 
  path: /weather/Grenoble/wind
  model: Wind_Speed
  
- name: Wind Berlin
  path: /weather/Berlin/wind
  model: Wind_Speed          
# drivers are in drivers folder
card:
- name: weather
  exec: weather/weather.rb
  location: "Paris,Grenoble,Berlin"
  timeout: 10
  plug: 
    /temperature_Paris: /weather/Paris/temperature
    /temperature_Grenoble: /weather/Grenoble/temperature
    /temperature_Berlin: /weather/Berlin/temperature
    /humidity_Paris: /weather/Paris/humidity
    /humidity_Grenoble: /weather/Grenoble/humidity
    /humidity_Berlin: /weather/Berlin/humidity
    /wind_Paris: /weather/Paris/wind
    /wind_Grenoble: /weather/Grenoble/wind
    /wind_Berlin: /weather/Berlin/wind
# plugins are in plugins folder
plugins:

- name: sql
  method: disable
  exec: sql.rb

- name: fill_sql
  method: disable
  exec: fill_sql.rb

- name: ror_frontend
  method: disable
  exec: ror_frontend.rb

- name: log
  method: disable
  exec: log.rb
  file: /tmp/opos2.log
  
- name: xmlrpc
  method: disable
  exec: xmlrpc.rb
  port: 8080
  
- name: soap
  method: disable
  exec: soap.rb
  port: 8081

user:

#no password
- login: anonymous
  permissions:
    read: all
    
# password : test
- login: user1
  hash: '325636066ccb24500a9f1a0df376965118e59230'
  permissions:
    read: all
    write: actuators
    exclude: /home/indoor/Fan

# password : test
- login: user2
  hash: '325636066ccb24500a9f1a0df376965118e59230'
  permissions:
    read: /home/outdoor/

# password : password
- login: admin
  hash: '5e38fb24e0314e2b3ec2caa2931c147442960ed4'
  permissions:
    write: all
