objects:

- name: Temperature Indoor
  path: /home/indoor/Temperature
  model: Generic_Celsius_Temperature
  regul:
    action-: /home/indoor/Fan
    frequency: 2
    type: "pwm_regul"
   
- name: Temperature Outdoor
  path: /home/outdoor/Temperature
  model: Generic_Celsius_Temperature

- name: Hygrometrie Outdoor
  path: /home/outdoor/Hygro
  model: VirtualPlacos_Hygro
  depends:
    temp: /home/outdoor/Temperature
     
- name: Hygrometrie Indoor
  path: /home/indoor/Hygro
  model: VirtualPlacos_Hygro
  depends:
    temp: /home/indoor/Temperature
  regul:
    action-: /home/indoor/Fan
    frequency: 0.5
  plugin_fill_sql_frequency: 2

    
- name: Light
  path: /home/indoor/Light
  model: Generic_relay_NO
    
- name: Fan
  path: /home/indoor/Fan
  model: Generic_pwm

card:
- name: VirtualPlacos
  exec: ../drivers/VirtualPlacos/VirtualPlacos.rb
  config: config.yaml
  timeout: 2
  plug: 
    /Pin_1: /home/indoor/Temperature
    /Pin_2: /home/outdoor/Temperature
    /Pin_3: /home/indoor/Light
    /Pin_4: /home/indoor/Fan
    /Pin_5: /home/outdoor/Hygro
    /Pin_6: /home/indoor/Hygro

plugins:

- name: sql
  method: fork
  exec: plugins/sql.rb

- name: fill_sql
  method: disable
  exec: plugins/fill_sql.rb

- name: ror_frontend
  method: disable
  exec: plugins/ror_frontend.rb

- name: log
  method: thread
  exec: plugins/log.rb
  file: /tmp/opos2.log
  
- name: xmlrpc
  method: fork
  exec: plugins/xmlrpc.rb
  port: 8080
  
- name: soap
  method: disable
  exec: plugins/soap.rb
  port: 8081

user:

#no password
- login: anonymous
  permissions:
    read: all
    exclude: /home/indoor/Temperature

# password : test
- login: user1
  hash: "a94a8fe5ccb19ba61c4c0873d391e987982fbbd3" 
  permissions:
    read: all
    write: actuators
    exclude: /home/indoor/Fan

# password : password
- login: admin
  hash: "5baa61e4c9b93f3f0682250b6cf8331b7ee68fd8"
  permissions:
    read: all
    write: all

